CREATE TABLE USERS(
	UID MEDIUMINT NOT NULL AUTO_INCREMENT,
    FirstName VARCHAR(25) NOT NULL,
    LastName VARCHAR(25) NOT NULL,
    Email VARCHAR(100) NOT NULL,
    Bios VARCHAR(500),
    PRIMARY KEY (UID)
);


CREATE TABLE GROCERIES(
	UPC BIGINT NOT NULL,
    Name VARCHAR(25) NOT NULL,
    Brand VARCHAR(25) NOT NULL,
    PRIMARY KEY (UPC)
);

CREATE TABLE OWNS(
	UPC BIGINT NOT NULL,
    UID MEDIUMINT NOT NULL,
    ExpireDate DATE NOT NULL,
    ItemCount INT NOT NULL,
    PRIMARY KEY (UPC, UID, ExpireDate),
    FOREIGN KEY (UPC) REFERENCES GROCERIES(UPC)
    ON DELETE CASCADE,
    FOREIGN KEY (UID) REFERENCES USERS(UID)
    ON DELETE CASCADE
);

CREATE TABLE RECIPE(
	RID MEDIUMINT NOT NULL,
    UPC BIGINT NOT NULL,
    PRIMARY KEY (RID, UPC),
    FOREIGN KEY (UPC) REFERENCES GROCERIES(UPC)
);

CREATE TABLE RATING(
	RID MEDIUMINT NOT NULL,
    Rating INT UNIQUE NOT NULL,
    PRIMARY KEY (RID),
    FOREIGN KEY (RID) REFERENCES RECIPE(RID)
    ON DELETE CASCADE
);

CREATE TABLE DIETICIAN(
    DID MEDIUMINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    FirstName VARCHAR(25) NOT NULL,
    LastName VARCHAR(25) NOT NULL
);

CREATE TABLE CHAT(
	CID MEDIUMINT NOT NULL AUTO_INCREMENT,
    UID MEDIUMINT NOT NULL,
    DID MEDIUMINT NOT NULL,
    Text VARCHAR(500) NOT NULL,
    Time TIMESTAMP NOT NULL,
    PRIMARY KEY (CID, UID, DID),
    FOREIGN KEY (UID) REFERENCES USERS(UID)
    ON DELETE CASCADE,
    FOREIGN KEY (DID) REFERENCES DIETICIAN(DID)
    ON DELETE CASCADE
);

CREATE TABLE PREFERENCE(
    UID MEDIUMINT NOT NULL PRIMARY KEY,
    Pref VARCHAR(25) NOT NULL,
    FOREIGN KEY (UID) REFERENCES USERS(UID)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

INSERT INTO
USERS(FirstName, LastName, Email)
VALUES
('Test', 'test', 'testing@gmail.com'),
('Test2', 'test2', 'testing2@gmail.com');

INSERT INTO
GROCERIES(UPC, Name, Brand)
VALUES
(123456789012, 'test2', 'testing');

INSERT INTO
OWNS(UPC, UID,ExpireDate,ItemCount)
VALUES
(123456789012, 2, '2023-10-14', 5);

DELETE 
FROM OWNS 
WHERE UID=1 AND UPC=123456789012 AND ExpireDate='2023-10-26' AND ItemCount=8
-- SELECT * FROM users

/*
-- Get a list of all tables in the database and generate DROP TABLE statements for each one.
SELECT CONCAT('DROP TABLE IF EXISTS `', table_name, '`;') 
FROM information_schema.tables 
WHERE table_schema = 'grocerymanger'; 

--delete all tables 
DROP TABLE IF EXISTS `chat`;
DROP TABLE IF EXISTS `dietician`;
DROP TABLE IF EXISTS `owns`;
DROP TABLE IF EXISTS `rating`;
DROP TABLE IF EXISTS `recipe`;
DROP TABLE IF EXISTS `groceries`;
DROP TABLE IF EXISTS `users`;*/